// 1. Defina os recursos de tradução
const resources = {
  'pt-BR': {
    translation: {
      title_config: "Configurações",
      general_settings: "Configurações Gerais",
      notifications: "Notificações",
      label_language: "Idioma",
      option_ptbr: "Português (Brasil)",
      option_enus: "Inglês (EUA)",
      label_theme: "Tema",
      option_light: "Claro",
      option_dark: "Escuro",
      label_timezone: "Fuso Horário",
      option_sp: "São Paulo (GMT-3)",
      option_ny: "Nova York (GMT-4)",
      notify_email: "Receber notificações por e-mail",
      notify_system: "Receber notificações no sistema",
      btn_save: "Salvar Alterações",
      menu_dashboard: "Dashboard",
      menu_tickets: "Meus Chamados",
      menu_new_ticket: "Abrir Chamado",
      menu_report: "Relatório do Analista",
      menu_faq: "FAQ",
      menu_logout: "Sair",
      dashboard_title: "Dashboard - Sistema de Chamados",
      dashboard_help_title: "O que você pode fazer aqui?",
      dashboard_welcome: "Bem-vindo(a) ao Sistema de Gerenciamento de Chamados!",
      dashboard_intro: "Após fazer login com suas credenciais corporativas, você está no seu Painel Principal (Dashboard). Veja o que você pode fazer:",
      dashboard_summary_title: "Ver Resumo dos Chamados:",
      dashboard_summary_desc: "O painel mostra uma visão rápida dos seus chamados abertos, em andamento, resolvidos e fechados. Gráficos e estatísticas podem aparecer aqui também.",
      dashboard_new_ticket_title: "Abrir Novo Chamado - Sistema de Chamados",
      dashboard_new_ticket_desc: "Use o botão Abrir Novo Chamado para reportar um problema ou fazer uma solicitação de serviço. Você preencherá um formulário escolhendo a categoria (ex: TI, RH), descrevendo a necessidade, definindo a urgência e anexando arquivos se necessário.",
      dashboard_btn_new_ticket: "Abrir Novo Chamado",
      dashboard_follow_title: "Acompanhar Chamados Existentes:",
      dashboard_follow_desc: "Você pode ver todos os chamados que enviou e seus status atuais. Clique em um chamado para ver detalhes, adicionar comentários ou enviar mais arquivos.",
      dashboard_notify_title: "Receber Notificações:",
      dashboard_notify_desc: "Qualquer atualização (como respostas de técnicos ou mudanças de status) geram notificações, geralmente por e-mail e/ou alertas visíveis no sistema.",
      dashboard_help_resources_title: "Acessar Recursos de Ajuda:",
      dashboard_help_resources_desc: "Do Usuário diretamente do painel.",
      dashboard_profile_title: "Editar Configurações do Perfil:",
      dashboard_profile_desc: "Você pode atualizar suas informações pessoais, trocar a senha ou ajustar preferências de notificação no seu Perfil.",
      dashboard_recent_activity: "Atividade Recente",
      dashboard_no_activity: "Nenhuma atividade recente para mostrar.",
      stat_open: "Abertos",
      stat_pending: "Em Atendimento",
      stat_resolved: "Resolvidos",
      stat_closed: "Fechados",
      ticket_list_title: "Meus Chamados - Sistema de Chamados",
      ticket_list_header: "Histórico de Chamados",
      ticket_list_filters: "Filtros",
      ticket_list_id: "ID",
      ticket_list_title_col: "Título",
      ticket_list_status: "Status",
      ticket_list_priority: "Prioridade",
      ticket_list_category: "Categoria",
      ticket_list_agent: "Agente",
      ticket_list_created: "Criado Em",
      ticket_list_updated: "Atualizado Em",
      ticket_list_loading: "Carregando chamados...",
      ticket_list_none: "Nenhum chamado em aberto.",
      ticket_list_error: "Erro ao carregar chamados.",
      ticket_list_pagination: "Exibindo X de Y chamados.",
      loading: "Carregando...",
      ticket_detail_title: "Detalhes do Chamado - Sistema de Chamados",
      ticket_detail_header: "Detalhes do Chamado",
      ticket_detail_loading: "Carregando detalhes do chamado...",
      ticket_detail_description: "Descrição",
      ticket_detail_attachments: "Anexos",
      ticket_detail_history: "Histórico do Chamado",
      ticket_detail_loading_history: "Carregando histórico...",
      ticket_detail_add_comment: "Adicionar Comentário / Resposta",
      ticket_detail_comment_placeholder: "Digite seu comentário aqui...",
      ticket_detail_attach_file: "Anexar arquivo (opcional)",
      ticket_detail_upload_disabled: "Upload de anexos desabilitado na simulação.",
      ticket_detail_send_comment: "Enviar Comentário",
      ticket_detail_info: "Informações",
      ticket_detail_priority: "Prioridade:",
      ticket_detail_category: "Categoria:",
      ticket_detail_requester: "Solicitante:",
      ticket_detail_agent: "Agente:",
      ticket_detail_created: "Criado em:",
      ticket_detail_updated: "Última Atualização:",
      ticket_detail_edit: "Editar Chamado",
      ticket_detail_close: "Fechar Chamado",
      ticket_detail_reopen: "Reabrir Chamado",
      report_title: "Relatório do Analista - Sistema de Chamados",
      report_summary_title: "Resumo de Atendimentos",
      report_total_tickets: "Total de chamados atendidos:",
      report_resolved_tickets: "Chamados resolvidos:",
      report_pending_tickets: "Chamados pendentes:",
      report_avg_resolution_time: "Média de tempo de resolução:",
      report_user_satisfaction: "Satisfação dos usuários:",
      report_last_tickets: "Últimos chamados atendidos",
      report_notes: "Observações do Analista",
      report_notes_placeholder: "Adicione observações ou comentários sobre o atendimento...",
      profile_title: "Perfil - Sistema de Chamados",
      profile_info: "Informações do Perfil",
      profile_name: "Nome",
      profile_email: "E-mail",
      profile_department: "Departamento",
      profile_role: "Função",
      profile_change_password: "Alterar Senha",
      profile_current_password: "Senha Atual",
      profile_new_password: "Nova Senha",
      profile_confirm_password: "Confirmar Nova Senha",
      profile_btn_change_password: "Alterar Senha",
      profile_name_placeholder: "Digite seu nome",
      profile_email_placeholder: "Digite seu e-mail",
      profile_department_placeholder: "Digite seu departamento",
      profile_role_placeholder: "Digite sua função",
      profile_current_password_placeholder: "Digite sua senha atual",
      profile_new_password_placeholder: "Digite sua nova senha",
      profile_confirm_password_placeholder: "Confirme sua nova senha",
      new_ticket_title: "Abrir Novo Chamado - Sistema de Chamados",
      new_ticket_details: "Detalhes da Solicitação",
      select_category: "Selecione a categoria",
      select_subcategory: "Selecione a subcategoria",
      priority_low: "Baixa",
      priority_medium: "Média",
      priority_high: "Alta",
      priority_critical: "Crítica",
      ticket_detail_title_col: "Título",
      ticket_detail_title_placeholder: "Um breve resumo do problema ou solicitação",
      ticket_detail_description_placeholder: "Descreva detalhadamente o problema ou solicitação. Inclua informações relevantes como mensagens de erro, passos para reproduzir o problema, etc.",
      ticket_detail_file_formats: "Formatos permitidos: PDF, JPG, PNG, DOC, DOCX, XLS, XLSX, TXT. Tamanho máximo: 5MB por arquivo.",
      btn_cancel: "Cancelar",
      btn_send_ticket: "Enviar Chamado",
      ticket_detail_subcategory: "Subcategoria",
      faq_title: "FAQ - Sistema de Chamados",
      faq_intro: "Encontre respostas para dúvidas comuns sobre o uso do Sistema de Gerenciamento de Chamados Corporativo.",
      faq_first_steps: "Primeiros Passos",
      faq_q1: "Como faço login no sistema?",
      faq_a1: "Você pode acessar o sistema com suas credenciais corporativas (usuário e senha) através da página de login: [Link da Página de Login]. Em caso de problemas, entre em contato com o suporte de TI.",
      faq_q2: "Qual é o principal objetivo deste sistema?",
      faq_a2: "O sistema foi criado para facilitar o registro, acompanhamento e resolução de solicitações internas em diferentes departamentos, como TI, RH e Facilities.",
      faq_q3: "Onde posso encontrar o manual do usuário?",
      faq_a3: "O manual completo está disponível na seção de Ajuda do sistema, geralmente acessível pelo menu principal ou rodapé. Você também pode acessá-lo aqui: [Link do Manual].",
      faq_opening_tickets: "Abertura de Chamados",
      faq_q4: "Como abro um novo chamado?",
      faq_a4: "Clique no botão 'Novo Chamado' ou 'Criar Solicitação' no seu dashboard principal. Preencha os campos obrigatórios como categoria, título, descrição e anexe arquivos se necessário.",
      faq_q5: "Que informações devo incluir em um chamado?",
      faq_a5: "Inclua:",
      faq_a5_1: "Um título claro e objetivo;",
      faq_a5_2: "Descrição detalhada da solicitação ou problema;",
      faq_a5_3: "Passos realizados antes do erro (se aplicável);",
      faq_a5_4: "Mensagens de erro (se houver);",
      faq_a5_5: "Capturas de tela ou arquivos relacionados;",
      faq_a5_6: "Nível de urgência ou impacto do problema.",
      faq_q6: "Posso definir a prioridade do chamado?",
      faq_a6: "Sim, ao criar o chamado, você pode escolher a prioridade (Baixa, Média, Alta ou Crítica) de acordo com o impacto causado.",
      faq_managing_tickets: "Gerenciamento de Chamados",
      faq_q7: "Como acompanho o status de um chamado?",
      faq_a7: "Todos os seus chamados podem ser visualizados na tela 'Meus Chamados' com seus respectivos status (Abertos, Em Progresso, Resolvidos, Fechados).",
      faq_q8: "Como adiciono comentários ou anexos a um chamado?",
      faq_a8: "Acesse o chamado desejado. Haverá uma área para comentários ou respostas, onde você pode incluir novas informações ou anexar arquivos.",
      faq_q9: "Como serei notificado sobre atualizações do chamado?",
      faq_a9: "Você receberá notificações por e-mail sempre que o chamado for atualizado. As preferências podem ser ajustadas nas configurações da sua conta.",
      faq_q10: "O que significam os diferentes status dos chamados?",
      faq_a10_1: "<strong>Aberto:</strong> Chamado criado e aguardando atendimento;",
      faq_a10_2: "<strong>Em Progresso:</strong> Um técnico está trabalhando na solicitação;",
      faq_a10_3: "<strong>Pendente:</strong> Aguardando retorno ou mais informações;",
      faq_a10_4: "<strong>Resolvido:</strong> A solicitação foi atendida e está pronta para fechamento;",
      faq_a10_5: "<strong>Fechado:</strong> Chamado fechado automaticamente ou após confirmação.",
      faq_troubleshooting: "Solução de Problemas",
      faq_q11: "Esqueci minha senha. Como a redefino?",
      faq_a11: "Se o sistema usar credenciais separadas, clique em 'Esqueci minha senha' na tela de login. Se estiver usando login corporativo, siga o processo padrão da sua empresa ou entre em contato com o suporte de TI.",
      faq_q12: "Estou vendo uma mensagem de erro. O que devo fazer?",
      faq_a12: "Tire uma captura de tela do erro. Tente atualizar a página ou limpar o cache do navegador. Se o problema persistir, abra um chamado com o máximo de detalhes possível e anexe a imagem do erro, informando também o que você estava tentando fazer na ocasião.",
      faq_q13: "Quem posso contatar para mais ajuda?",
      faq_a13: "Se sua dúvida não foi respondida nesta página, vá até a <a href=\"[Link da Página de Suporte]\">Página de Suporte</a> ou abra um novo chamado na categoria 'Suporte ao Sistema'.",
      profile_profile: "Perfil",
      notification_title: "Notificações",
      menu_config: "Configurações",
      menu_logout: "Sair",
      // ...dentro de translation: {
      notification_title: "Notificações",
      notification_none: "Nenhuma notificação no momento.",
      notification_mark_all_read: "Marcar todas como lidas",
      notification_new: "Nova notificação",
      notification_view_all: "Ver todas as notificações",
// ...restante das chaves...



    }
  },
  'en-US': {
    translation: {
      // Para en-US
profile_profile: "Profile",
notification_title: "Notifications",
menu_config: "Settings",
menu_logout: "Logout",

      // ...existing code...
      notification_title: "Notifications - Ticket System",
      notification_none: "No notifications at the moment.",
      notification_mark_all_read: "Mark all as read",
      notification_new: "New notification",
      notification_view_all: "View all notifications",
// ...existing code...
      title_config: "Settings",
      general_settings: "General Settings",
      notifications: "Notifications",
      label_language: "Language",
      option_ptbr: "Portuguese (Brazil)",
      option_enus: "English (US)",
      label_theme: "Theme",
      option_light: "Light",
      option_dark: "Dark",
      label_timezone: "Time zone",
      option_sp: "São Paulo (GMT-3)",
      option_ny: "New York (GMT-4)",
      notify_email: "Receive notifications by email",
      notify_system: "Receive system notifications",
      btn_save: "Save Changes",
      menu_dashboard: "Dashboard",
      menu_tickets: "My Tickets",
      menu_new_ticket: "Open Ticket",
      menu_report: "Analyst Report",
      menu_faq: "FAQ",
      menu_logout: "Logout",
      dashboard_title: "Dashboard - Ticket System",
      dashboard_help_title: "What can you do here?",
      dashboard_welcome: "Welcome to the Ticket Management System!",
      dashboard_intro: "After logging in with your corporate credentials, you are on your Main Dashboard. Here’s what you can do:",
      dashboard_summary_title: "View Ticket Summary:",
      dashboard_summary_desc: "The dashboard gives you a quick overview of your open, in progress, resolved, and closed tickets. Charts and statistics may also appear here.",
      dashboard_new_ticket_title: "Create a New Ticket:",
      dashboard_new_ticket_desc: "Use the Open New Ticket button to report a problem or make a service request. You will fill out a form choosing the category (e.g., IT, HR), describing the need, setting the urgency, and attaching files if necessary.",
      dashboard_btn_new_ticket: "Open New Ticket",
      dashboard_follow_title: "Track Existing Tickets:",
      dashboard_follow_desc: "You can see all the tickets you have submitted and their current status. Click a ticket to view details, add comments, or upload more files.",
      dashboard_notify_title: "Receive Notifications:",
      dashboard_notify_desc: "Any update (such as technician responses or status changes) generates notifications, usually by email and/or visible alerts in the system.",
      dashboard_help_resources_title: "Access Help Resources:",
      dashboard_help_resources_desc: "Directly from the dashboard.",
      dashboard_profile_title: "Edit Profile Settings:",
      dashboard_profile_desc: "You can update your personal information, change your password, or adjust notification preferences in your Profile.",
      dashboard_recent_activity: "Recent Activity",
      dashboard_no_activity: "No recent activity to show.",
      stat_open: "Open",
      stat_pending: "In Progress",
      stat_resolved: "Resolved",
      stat_closed: "Closed",
      ticket_list_title: "My Tickets - Ticket System",
      ticket_list_header: "Ticket History",
      ticket_list_filters: "Filters",
      ticket_list_id: "ID",
      ticket_list_title_col: "Title",
      ticket_list_status: "Status",
      ticket_list_priority: "Priority",
      ticket_list_category: "Category",
      ticket_list_agent: "Agent",
      ticket_list_created: "Created At",
      ticket_list_updated: "Updated At",
      ticket_list_loading: "Loading tickets...",
      ticket_list_none: "No open tickets.",
      ticket_list_error: "Error loading tickets.",
      ticket_list_pagination: "Showing X of Y tickets.",
      loading: "Loading...",
      ticket_detail_title: "Ticket Details - Ticket System",
      ticket_detail_header: "Ticket Details",
      ticket_detail_loading: "Loading ticket details...",
      ticket_detail_description: "Description",
      ticket_detail_attachments: "Attachments",
      ticket_detail_history: "Ticket History",
      ticket_detail_loading_history: "Loading history...",
      ticket_detail_add_comment: "Add Comment / Reply",
      ticket_detail_comment_placeholder: "Type your comment here...",
      ticket_detail_attach_file: "Attach file (optional)",
      ticket_detail_upload_disabled: "Attachment upload disabled in simulation.",
      ticket_detail_send_comment: "Send Comment",
      ticket_detail_info: "Information",
      ticket_detail_priority: "Priority:",
      ticket_detail_category: "Category:",
      ticket_detail_requester: "Requester:",
      ticket_detail_agent: "Agent:",
      ticket_detail_created: "Created at:",
      ticket_detail_updated: "Last Updated:",
      ticket_detail_edit: "Edit Ticket",
      ticket_detail_close: "Close Ticket",
      ticket_detail_reopen: "Reopen Ticket",
      report_title: "Analyst Report - Ticket System",
      report_summary_title: "Service Summary",
      report_total_tickets: "Total tickets handled:",
      report_resolved_tickets: "Resolved tickets:",
      report_pending_tickets: "Pending tickets:",
      report_avg_resolution_time: "Average resolution time:",
      report_user_satisfaction: "User satisfaction:",
      report_last_tickets: "Last handled tickets",
      report_notes: "Analyst Notes",
      report_notes_placeholder: "Add notes or comments about the service...",
      profile_title: "Profile - Ticket System",
      profile_info: "Profile Information",
      profile_name: "Name",
      profile_email: "Email",
      profile_department: "Department",
      profile_role: "Role",
      profile_change_password: "Change Password",
      profile_current_password: "Current Password",
      profile_new_password: "New Password",
      profile_confirm_password: "Confirm New Password",
      profile_btn_change_password: "Change Password",
      profile_name_placeholder: "Enter your name",
      profile_email_placeholder: "Enter your email",
      profile_department_placeholder: "Enter your department",
      profile_role_placeholder: "Enter your role",
      profile_current_password_placeholder: "Enter your current password",
      profile_new_password_placeholder: "Enter your new password",
      profile_confirm_password_placeholder: "Confirm your new password",
      new_ticket_title: "Open New Ticket - Ticket System",
      new_ticket_details: "Request Details",
      select_category: "Select category",
      select_subcategory: "Select subcategory",
      priority_low: "Low",
      priority_medium: "Medium",
      priority_high: "High",
      priority_critical: "Critical",
      ticket_detail_title_col: "Title",
      ticket_detail_title_placeholder: "A brief summary of the problem or request",
      ticket_detail_description_placeholder: "Describe the problem or request in detail. Include relevant information such as error messages, steps to reproduce the problem, etc.",
      ticket_detail_file_formats: "Allowed formats: PDF, JPG, PNG, DOC, DOCX, XLS, XLSX, TXT. Max size: 5MB per file.",
      btn_cancel: "Cancel",
      btn_send_ticket: "Send Ticket",
      ticket_detail_subcategory: "Subcategory",
      faq_title: "FAQ - Ticket System",
      faq_intro: "Find answers to common questions about using the Corporate Ticket Management System.",
      faq_first_steps: "First Steps",
      faq_q1: "How do I log in to the system?",
      faq_a1: "You can access the system with your corporate credentials (username and password) on the login page: [Login Page Link]. If you have problems, contact IT support.",
      faq_q2: "What is the main purpose of this system?",
      faq_a2: "The system was created to facilitate the registration, tracking, and resolution of internal requests in different departments, such as IT, HR, and Facilities.",
      faq_q3: "Where can I find the user manual?",
      faq_a3: "The full manual is available in the Help section of the system, usually accessible from the main menu or footer. You can also access it here: [Manual Link].",
      faq_opening_tickets: "Opening Tickets",
      faq_q4: "How do I open a new ticket?",
      faq_a4: "Click the 'New Ticket' or 'Create Request' button on your main dashboard. Fill in the required fields such as category, title, description, and attach files if necessary.",
      faq_q5: "What information should I include in a ticket?",
      faq_a5: "Include:",
      faq_a5_1: "A clear and objective title;",
      faq_a5_2: "Detailed description of the request or problem;",
      faq_a5_3: "Steps taken before the error (if applicable);",
      faq_a5_4: "Error messages (if any);",
      faq_a5_5: "Screenshots or related files;",
      faq_a5_6: "Level of urgency or impact of the problem.",
      faq_q6: "Can I set the ticket priority?",
      faq_a6: "Yes, when creating the ticket, you can choose the priority (Low, Medium, High, or Critical) according to the impact caused.",
      faq_managing_tickets: "Managing Tickets",
      faq_q7: "How do I track the status of a ticket?",
      faq_a7: "All your tickets can be viewed on the 'My Tickets' screen with their respective status (Open, In Progress, Resolved, Closed).",
      faq_q8: "How do I add comments or attachments to a ticket?",
      faq_a8: "Access the desired ticket. There will be an area for comments or replies, where you can include new information or attach files.",
      faq_q9: "How will I be notified about ticket updates?",
      faq_a9: "You will receive email notifications whenever the ticket is updated. Preferences can be adjusted in your account settings.",
      faq_q10: "What do the different ticket statuses mean?",
      faq_a10_1: "<strong>Open:</strong> Ticket created and awaiting service;",
      faq_a10_2: "<strong>In Progress:</strong> A technician is working on the request;",
      faq_a10_3: "<strong>Pending:</strong> Waiting for feedback or more information;",
      faq_a10_4: "<strong>Resolved:</strong> The request has been handled and is ready to be closed;",
      faq_a10_5: "<strong>Closed:</strong> Ticket automatically closed or after confirmation.",
      faq_troubleshooting: "Troubleshooting",
      faq_q11: "I forgot my password. How do I reset it?",
      faq_a11: "If the system uses separate credentials, click 'Forgot my password' on the login screen. If using corporate login, follow your company's standard process or contact IT support.",
      faq_q12: "I'm seeing an error message. What should I do?",
      faq_a12: "Take a screenshot of the error. Try refreshing the page or clearing your browser cache. If the problem persists, open a ticket with as many details as possible and attach the error image, also informing what you were trying to do at the time.",
      faq_q13: "Who can I contact for more help?",
      faq_a13: "If your question is not answered on this page, go to the <a href=\"[Support Page Link]\">Support Page</a> or open a new ticket in the 'System Support' category.",
    }
  }
};

function updateContent() {
  // Atualiza textos com data-i18n
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = i18next.t(key);
  });
  // Atualiza placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.setAttribute('placeholder', i18next.t(key));
  });
  // Atualiza o valor do select de idioma, se existir
  const langSelect = document.getElementById('language');
  if (langSelect) langSelect.value = i18next.language;
}

// 2. Inicialize o i18next SEMPRE lendo do localStorage
document.addEventListener('DOMContentLoaded', function() {
  i18next.init({
    lng: localStorage.getItem('selectedLanguage') || 'pt-BR',
    resources
  }, function(err, t) {
    updateContent();
  });

  // 3. Troca de idioma ao selecionar no select
  const langSelect = document.getElementById('language');
  if (langSelect) {
    langSelect.addEventListener('change', function() {
      i18next.changeLanguage(this.value, updateContent);
      localStorage.setItem('selectedLanguage', this.value);
    });
  }
});

// 4. Se carregar sidebar/menu via AJAX, chame updateContent() após inserir no DOM
